

FACEDOWN = 0
FACEUPTOCONTROLLER = 1
FACEUPTOEVERYONE = 2
FACEUPTOOPPONENT = 3

CCZDESTROY = 'Destroy card'
CCZBANISH = 'Banish card'
CCZDISCARD = 'Discard card'
CCZRETURNTOHAND = 'Return card to hand'

STATE_NOTINEFFECT = 0
STATE_EVENT = 1
STATE_ACTIVATE = 2
STATE_RESOLVE = 3

CAUSE_CHAIN = 0
CAUSE_EFFECT = 1
CAUSE_BATTLE = 2
CAUSE_TRIBUTE = 3
