

FACEDOWN = 0
FACEUPTOCONTROLLER = 1
FACEUPTOEVERYONE = 2
FACEUPTOOPPONENT = 3

CCZTRIBUTE = 'Tribute card'
CCZDESTROY = 'Destroy card'
CCZBANISH = 'Banish card'
CCZDISCARD = 'Discard card'
CCZRETURNTOHAND = 'Return card to hand'

CAUSE_CHAIN = 0
CAUSE_EFFECT = 1
CAUSE_BATTLE = 2
CAUSE_TRIBUTE = 3
